### ISSUE TITLE
the new release

### ISSUE THREAD

**Issue by Suspectxyzz** [Mzzzj/CS2_DMA_Radar#10]
the new release problem on start how to fix this ? 
![NVIDIA_Share_sQU8RT7ily](https://github.com/Mzzzj/CS2_DMA_Radar/assets/45514952/3c26aff2-f699-474c-a534-92e2c7b59b5b)
![NVIDIA_Share_YXbW5xnOdN](https://github.com/Mzzzj/CS2_DMA_Radar/assets/45514952/c7e4a0ba-bcce-4246-9444-f87f75eb4b5c)
![NVIDIA_Share_gvQOyh85Wu](https://github.com/Mzzzj/CS2_DMA_Radar/assets/45514952/6e107725-a49e-4c1e-9d70-91170c5c27ad)

**Comment by xCorteX** [comment]
its for share to your frainds 
open localhost:8080 then press "cancel" or use "192.168.50.218:8899"

**Comment by Suspectxyzz** [comment]
> its for share to your friends open localhost:8080 then press "cancel" or use "192.168.50.218:8899"
https://img.meowless.club/chrome_2RexiiDpsL.png
