### ISSUE TITLE
Need to update

### ISSUE THREAD

**Issue by HH333** [Mzzzj/CS2_DMA_Radar#12]
Need to update

**Comment by HH333** [comment]
Offsets updated, but map and enemy location information cannot be loaded.

**Comment by xCorteX** [comment]
update the map offset 
`public  static long mapNameVal=0x1D2300`

**Comment by gaoyuxiang120** [comment]
> update the map offset `public static long mapNameVal=0x1D2300`

hey mate, how to get mapnameval? i know ce would work, but dont know how. do you have some tips?
