### ISSUE TITLE
无地图显示问题

### ISSUE THREAD

**Issue by IDhammaI** [Mzzzj/CS2_DMA_Radar#13]
我使用的是release版本，我安装了jdk20，cmd内java -verson显示的是jdk20 (jdk环境ok)，运行后也没抛出什么错误，然而地图是空的，dma连接是正常的，真的很奇怪，寻求帮助
![image](https://github.com/Mzzzj/CS2_DMA_Radar/assets/124808841/9a3df9ad-e673-4364-aed9-682bb7629a6d)

**Comment by Mzzzj** [comment]
你需要自己更新获取地图名的偏移

**Comment by IDhammaI** [comment]
已解决，谢谢

**Comment by hanruxian** [comment]
怎么解决的我也是这种问题
