### ISSUE TITLE
请问可以给我联系方式吗，有偿请教一些东西

### ISSUE THREAD

**Issue by IDhammaI** [Mzzzj/CS2_DMA_Radar#16]
如果愿意，发邮箱到1518470138@qq.com您的联系方式，如果不愿意，您可以直接关闭此issue

**Comment by IDhammaI** [comment]
![image](https://github.com/Mzzzj/CS2_DMA_Radar/assets/124808841/f922580d-5f15-44f7-8432-f053a186fcc7)
无法添加您的qq

**Comment by jinbao322** [comment]
我是请教你，不是你请教我。。。。你是大佬吧？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: IDhammaI ***@***.***&gt;
发送时间: 2024年2月21日 07:37
收件人: Mzzzj/CS2_DMA_Radar ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Mzzzj/CS2_DMA_Radar] 请问可以给我联系方式吗，有偿请教一些东西 (Issue #16)

**Comment by IDhammaI** [comment]
....我会一些东西，我只是找作者咨询点代码层面的东西
&nbsp;


1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月21日(星期三) 上午7:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Mzzzj/CS2_DMA_Radar] 请问可以给我联系方式吗，有偿请教一些东西 (Issue #16)





 我是请教你，不是你请教我。。。。你是大佬吧？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: IDhammaI ***@***.***&amp;gt; 
 发送时间: 2024年2月21日 07:37 
 收件人: Mzzzj/CS2_DMA_Radar ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: Re: [Mzzzj/CS2_DMA_Radar] 请问可以给我联系方式吗，有偿请教一些东西 (Issue #16)

**Comment by IDhammaI** [comment]
你遇到啥问题了，说不定我可以帮你解决&nbsp;


QQ 1518470138

1518470138
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mzzzj/CS2_DMA_Radar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月21日(星期三) 上午7:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mzzzj/CS2_DMA_Radar] 请问可以给我联系方式吗，有偿请教一些东西 (Issue #16)





 我是请教你，不是你请教我。。。。你是大佬吧？ 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: IDhammaI ***@***.***&amp;gt; 
 发送时间: 2024年2月21日 07:37 
 收件人: Mzzzj/CS2_DMA_Radar ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: Re: [Mzzzj/CS2_DMA_Radar] 请问可以给我联系方式吗，有偿请教一些东西 (Issue #16)

**Comment by IDhammaI** [comment]
....我会一些东西，我只是找作者咨询点代码层面的东西

**Comment by IDhammaI** [comment]
你遇到啥问题了

**Comment by IDhammaI** [comment]
@jinbao322 你遇到什么问题了
