### ISSUE TITLE
Players Location On The Map

### ISSUE THREAD

**Issue by blueeorx1** [Mzzzj/CS2_DMA_Radar#3]
Hello Please help me
I have everything is work fine but once i go to a match the map loaded but there is no players on the radar map
Only Empty map
It was working before but now no any solution to this problem please ?
I have updated the dwEntityList +  dwLocalPlayerPawn btw
Thank you

**Comment by xCorteX** [comment]
update the offsets in
CS2DMA/src/main/java/cs2/dma/main/PlayerAddressUpdateThread.java

**Comment by blueeorx1** [comment]
I've replaced your file with mine now when i run java -jar cs2dma-1.0.jar nothing happen

**Comment by xCorteX** [comment]
dont repleace it, edit only the offsets

                memoryTool.readInt(EntityAddress + 0x7C8, 4),
                memoryTool.readInt(EntityAddress + 0x7CC, 4),
                memoryTool.readInt(EntityAddress + 0x7C4, 4) != 0,

**Comment by rabume** [comment]
@blueeorx1 

I updated the offsets in my fork. Should work for you too:
https://github.com/rabume/cs2-dma-radar/blob/main/app/src/main/java/cs2/dma/main/PlayerAddressUpdateThread.java

**Comment by rabume** [comment]
Tbh idk. I just saw that before update the offset for 'm_angEyeAngles' was '0x1500' and in the codebase '0x1504' was used. I also saw that on certain other offsets '0x4' were added. So I just tried it with the new 'm_angEyeAngles' offset and it worked 😄
