### ISSUE TITLE
无地图问题

### ISSUE THREAD

**Issue by mn2xujiakun** [Mzzzj/CS2_DMA_Radar#9]
看到您发了一个jar版本，但是和我自己build的jar文件有一样的问题，如果不把jar放到RadarJava这个文件夹里就会加载不出来地图
![image](https://github.com/Mzzzj/CS2_DMA_Radar/assets/36425068/5f94f8ba-3d22-4ffb-91af-67253183bcef)
只有这样放才能不出问题

**Comment by Mzzzj** [comment]
因为他要试用vmm路径下的动态链接库

**Comment by mn2xujiakun** [comment]
![image](https://github.com/Mzzzj/CS2_DMA_Radar/assets/36425068/c36c5e82-5d52-475d-a728-6658af8ad62e)

**Comment by Mzzzj** [comment]
更新json偏移文件

**Comment by mn2xujiakun** [comment]
> 更新json偏移文件

哦哦我忘记更新偏移了，感谢感谢
